import { Injectable } from '@angular/core';
import { acabamentoPuxador, acabamentoPuxadorInferior, acabamentosCorpo, acabamentosCorrediça, acabamentosDivisorAcrilico, acabamentosDivisorGaveta, acabamentosDivisorTalher, acabamentosEspelho, acabamentosEstofaria, acabamentosInterruptor, acabamentosLixeira, acabamentosPassaFio, acabamentosPortaDeslizante, acabamentosPortaPassagem, acabamentosPortaTempero, acabamentosSerralheria, acabamentosTabuaPassar, acabamentosTomada, acabamentosTulha, acabamentosVidro, afastamentoFrontalRodateto, afastamentoRodape, alturafinalPedra, alturaRodape, alturaRodateto, coresMDF, coresPerfil, corposPorta, corposPortaDeslizante, corposPortaPassagem, espessuraPedra, espessurasEspelho, espessurasVidro, existentePedra, fechadurasPortaDeslizante, fechadurasPortaPassagem, Fornecedor, fornecedoresDivisorAcrilico, fornecedoresDivisorGaveta, fornecedoresDivisorTalher, fornecedoresEspelho, fornecedoresEstofaria, fornecedoresIluminacao, fornecedoresInterruptor, fornecedoresLixeira, fornecedoresPassaFio, fornecedoresPedra, fornecedoresPortaTempero, fornecedoresPuxadorInferior, fornecedoresSerralheria, fornecedoresTulha, fornecedoresVidro, fornecedorTabuaPassar, fornecedorTomada, instaladoresEstofaria, instaladoresSerralheria, margemBox, modeloPerfil, modeloPuxadorInferior, modeloPuxadorSuperior, modelosBox, modelosCorrediça, modelosDivisorAcrilico, modelosDivisorGaveta, modelosDivisorTalher, modelosEstofaria, modelosIluminacao, modelosInterruptor, modelosLixeira, modelosPassaFio, modelosPedra, modelosPortaTempero, modelosPuxadorPerfil, modelosRodape, modelosRodaTeto, modelosSerralheria, modelosTabuaPassar, modelosTomada, modelosTulha, nomesSistemasPortaDeslizante, quantidadeDivisorAcrilico, quantidadeDivisorGaveta, quantidadeDivisorTalher, quantidadeInterruptor, quantidadeLixeira, quantidadePassaFio, quantidadePortaDeslizante, quantidadePortaPassagem, quantidadePortaTempero, quantidadePuxadorInferior, quantidadepuxadorsuperior, quantidadeTabuaPassar, quantidadeTomada, quantidadeTulha, recebeRodape, sistemasPortaDeslizante, sistemasPortaPassagem, temperaturasIluminacao } from '../data';

@Injectable({
  providedIn: 'root'
})
export class ListasOpcoesService {

  listasOpcoes = {
    modeloPuxadorSuperior: modeloPuxadorSuperior,
    acabamentoPuxador: acabamentoPuxador,
    Fornecedor: Fornecedor,
    quantidadepuxadorsuperior: quantidadepuxadorsuperior,
    modeloPuxadorInferior: modeloPuxadorInferior,
    acabamentoPuxadorInferior: acabamentoPuxadorInferior,
    coresMDF: coresMDF,
    quantidadePuxadorInferior: quantidadePuxadorInferior,
    modeloPerfil: modeloPerfil,
    modelosPuxadorPerfil: modelosPuxadorPerfil,
    espessuraPedra: espessuraPedra,
    coresPerfil: coresPerfil,
    acabamentosCorpo: acabamentosCorpo,
    espessurasVidro: espessurasVidro,
    acabamentosVidro: acabamentosVidro,
    espessurasEspelho: espessurasEspelho,
    acabamentosEspelho: acabamentosEspelho,
    nomesSistemasPortaDeslizante: nomesSistemasPortaDeslizante,
    corposPortaDeslizante: corposPortaDeslizante,
    acabamentosPortaDeslizante: acabamentosPortaDeslizante,
    fechadurasPortaDeslizante: fechadurasPortaDeslizante,
    sistemasPortaDeslizante: sistemasPortaDeslizante,
    corposPortaPassagem: corposPortaPassagem,
    sistemasPortaPassagem: sistemasPortaPassagem,
    acabamentosPortaPassagem: acabamentosPortaPassagem,
    fechadurasPortaPassagem: fechadurasPortaPassagem,
    modelosEstofaria: modelosEstofaria,
    acabamentosEstofaria: acabamentosEstofaria,
    fornecedoresEstofaria: fornecedoresEstofaria,
    fornecedoresPuxadorInferior: fornecedoresPuxadorInferior,
    corposPorta: corposPorta,
    fornecedoresVidro: fornecedoresVidro,
    fornecedoresEspelho: fornecedoresEspelho,
    quantidadePortaDeslizante: quantidadePortaDeslizante,
    quantidadePortaPassagem: quantidadePortaPassagem,
    instaladoresEstofaria: instaladoresEstofaria,
    modelosSerralheria: modelosSerralheria,
    acabamentosSerralheria: acabamentosSerralheria,
    fornecedoresSerralheria: fornecedoresSerralheria,
    instaladoresSerralheria: instaladoresSerralheria,
    modelosIluminacao: modelosIluminacao,
    temperaturasIluminacao: temperaturasIluminacao,
    fornecedoresIluminacao: fornecedoresIluminacao,
    modelosTomada: modelosTomada,
    fornecedorTomada: fornecedorTomada,
    acabamentosTomada: acabamentosTomada,
    quantidadeTomada: quantidadeTomada,
    modelosInterruptor: modelosInterruptor,
    acabamentosInterruptor: acabamentosInterruptor,
    fornecedoresInterruptor: fornecedoresInterruptor,
    quantidadeInterruptor: quantidadeInterruptor,
    modelosPassaFio: modelosPassaFio,
    acabamentosPassaFio: acabamentosPassaFio,
    fornecedoresPassaFio: fornecedoresPassaFio,
    quantidadePassaFio: quantidadePassaFio,
    modelosPortaTempero: modelosPortaTempero,
    acabamentosPortaTempero: acabamentosPortaTempero,
    fornecedoresPortaTempero: fornecedoresPortaTempero,
    quantidadePortaTempero: quantidadePortaTempero,
    modelosLixeira: modelosLixeira,
    acabamentosLixeira: acabamentosLixeira,
    fornecedoresLixeira: fornecedoresLixeira,
    alturaRodape: alturaRodape,
    afastamentoRodape: afastamentoRodape,
    alturaRodateto: alturaRodateto,
    afastamentoFrontalRodateto: afastamentoFrontalRodateto,
    alturafinalPedra: alturafinalPedra,
    quantidadeLixeira: quantidadeLixeira,
    modelosDivisorGaveta: modelosDivisorGaveta,
    acabamentosDivisorGaveta: acabamentosDivisorGaveta,
    fornecedoresDivisorGaveta: fornecedoresDivisorGaveta,
    quantidadeDivisorGaveta: quantidadeDivisorGaveta,
    modelosDivisorAcrilico: modelosDivisorAcrilico,
    acabamentosDivisorAcrilico: acabamentosDivisorAcrilico,
    fornecedoresDivisorAcrilico: fornecedoresDivisorAcrilico,
    quantidadeDivisorAcrilico: quantidadeDivisorAcrilico,
    modelosDivisorTalher: modelosDivisorTalher,
    acabamentosDivisorTalher: acabamentosDivisorTalher,
    fornecedoresDivisorTalher: fornecedoresDivisorTalher,
    quantidadeDivisorTalher: quantidadeDivisorTalher,
    modelosTulha: modelosTulha,
    acabamentosTulha: acabamentosTulha,
    fornecedoresTulha: fornecedoresTulha,
    quantidadeTulha: quantidadeTulha,
    modelosCorrediça: modelosCorrediça,
    acabamentosCorrediça: acabamentosCorrediça,
    modelosTabuaPassar: modelosTabuaPassar,
    acabamentosTabuaPassar: acabamentosTabuaPassar,
    fornecedorTabuaPassar: fornecedorTabuaPassar,
    quantidadeTabuaPassar: quantidadeTabuaPassar,
    existentePedra: existentePedra,
    modelosPedra: modelosPedra,
    fornecedoresPedra: fornecedoresPedra,
    margemBox: margemBox,
    modelosBox: modelosBox,
    modelosRodape:modelosRodape,
    recebeRodape:recebeRodape,
    modelosRodaTeto: modelosRodaTeto
  }

  getListaopcoes(){
    return this.listasOpcoes;
  }
}
